### ISSUE TITLE
Rewrite queries using transactions.

### ISSUE THREAD

**Issue by abhieshekumar** [MentorsWithoutBorders/mwb_connect_backend#8]
As of now queries which are intended to execute together might fail because they are not written as transactions. Rewriting queries using transactions will ensure that the database is in a consistent state.

**Comment by abhieshekumar** [comment]
@edmondpr can you assign this to me?

**Comment by edmondpr** [comment]
Thanks for creating this issue Abhishek, I've assigned it to you now.
